/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/GameOverPage': RouteRecordInfo<
      '/GameOverPage',
      '/GameOverPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/GamePage': RouteRecordInfo<
      '/GamePage',
      '/GamePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HistoryPage': RouteRecordInfo<
      '/HistoryPage',
      '/HistoryPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomePage': RouteRecordInfo<
      '/HomePage',
      '/HomePage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/StatsPage': RouteRecordInfo<
      '/StatsPage',
      '/StatsPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/GameOverPage.vue': {
      routes:
        | '/GameOverPage'
      views:
        | never
    }
    'src/pages/GamePage.vue': {
      routes:
        | '/GamePage'
      views:
        | never
    }
    'src/pages/HistoryPage.vue': {
      routes:
        | '/HistoryPage'
      views:
        | never
    }
    'src/pages/HomePage.vue': {
      routes:
        | '/HomePage'
      views:
        | never
    }
    'src/pages/StatsPage.vue': {
      routes:
        | '/StatsPage'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
