---
packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080  # 7 days (in minutes)

allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true

overrides:
  glob@^11.1.0: '^13.0.6'
  source-map-js@>=1.0.0 <1.2.2: ^1.2.2
