---
packages:
  - apps/*
  - packages/*

minimumReleaseAge: 7200  # 5 days (in minutes)
minimumReleaseAgeExclude:
  - '@biomejs/biome'
  - '@biomejs/cli-darwin-arm64'
  - '@biomejs/cli-darwin-x64'
  - '@biomejs/cli-linux-arm64-musl'
  - '@biomejs/cli-linux-arm64'
  - '@biomejs/cli-linux-x64-musl'
  - '@biomejs/cli-linux-x64'
  - '@biomejs/cli-win32-arm64'
  - '@biomejs/cli-win32-x64'

allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true

overrides:
  glob@^11.1.0: '^13.0.6'
