packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - cypress
  - esbuild

minimumReleaseAge: 20160 # 2 weeks (in minutes)
minimumReleaseAgeExclude:
  - '@biomejs/biome'
  - '@biomejs/cli-darwin-arm64'
  - '@biomejs/cli-darwin-x64'
  - '@biomejs/cli-linux-arm64-musl'
  - '@biomejs/cli-linux-arm64'
  - '@biomejs/cli-linux-x64-musl'
  - '@biomejs/cli-linux-x64'
  - '@biomejs/cli-win32-arm64'
  - '@biomejs/cli-win32-x64'
  - cypress@15.17.0
  - qs@6.15.2
  - tmp@0.2.6
  - yauzl@3.3.1
  - shell-quote

overrides:
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  qs@>=6.11.1 <=6.15.1: ^6.15.2
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  glob@^10.4.2: '^13.0.6'
  glob@^11.0.1: '^13.0.6'
  source-map@^0.8.0-beta.0: '0.7.4'
